### PR TITLE
Fix kernel.cpp for regtest

### PR DESCRIPTION
**Pull request by FornaxA**
When on regtest, break from loop when null ptr found for stake modifier.

### CODE REVIEW

**Review by ioncoincore — APPROVED** [review]

**Comment by cevap** [comment]
Just wondering why do we need old staking? My regtest staked without any issues before this commit, can somebody verify it?

**Comment by FornaxA** [comment]
I got the 'Null pindexNext' error when switching from PoW to PoS on regtest.
In all fairness, I do not really know why, and I admit this is a bit dirty.
I had the same issue once when setting up a testnet, when I created 100% of the staking blocks with 1 wallet. Then, I passed this error by creating 1 block with a second wallet..

**Comment by cevap** [comment]
You got it correctly, you should have at least some blocks aged 1 hour, then they will stake. Best is to premine all POW blocks except the last, wait 1 hour, mine last block and you will stake.

**Comment by ioncoincore** [comment]
I will close this one if @FornaxA  doesnt mind, as regtest works as the intention was, @FornaxA please reopen it if you for some reason want to use/test with old algorithms.

If adding this change, we should check if restarting testnet would cause same issue, which it would, on main too, I guess best is keeping it as it is as it works like intended.

**Pull request closed without merging**
