### PR TITLE
Document outlining upload and download of VM torrents

### PR DESCRIPTION
**Pull request by ckti**
Document outlining upload and download of VM torrents

### CODE REVIEW

**Review by CeForce — APPROVED** [review]

**Comment by ioncoincore** [comment]
@ckti can you click "Update branch", then it can be merged
grafik

**Review by ioncoincore — CHANGES_REQUESTED** [review]
click "Update branch"

**Review by ioncoincore — APPROVED** [review]

**Comment by ioncoincore** [comment]
@ckti all commits have to be signed

**Comment by ckti** [comment]
Closing this PR and creating a new one

**Pull request closed without merging**
