### PR TITLE
Added raid12345678 GPG key to the list of users

### PR DESCRIPTION
**Pull request by raid12345678**
I have added my gpg key to the gitian-keys/keys.txt file Nothing else was changed

### CODE REVIEW

**Comment by MitchellCash** [comment]
ACK b85047c31399cdc9e91e9cea26276ca01aa4c21b

**Review by MitchellCash — APPROVED** [review]

**Comment by MitchellCash** [comment]
@raid12345678 has this been pushed to a key server? I couldn't see it on one.

**Comment by raid12345678** [comment]
I just added my key to the ion/contrib/gitian-keys/keys.txt manually following these instructions from @boris 
1. fork ioncoincore/ion to your account
2. then git clone from your account
3. cd ion (go to ion in terminal)
4. create new branks: git checkout -b raid12345678-gpg
then add your fingerprint key at the end of the file contrib/gitian-keys/keys.txt
to see your fingerprint, run: gpg --list-keys
5. commit and push your branch raid12345678-gpg
6. make pull request to ioncoincore/ion master branch from raid12345678-gpg
if you have any troubles with any steps please let me know

first time doing this I dont want to mess anything up. Let me know if there is something wrong with it.

**Comment by MitchellCash** [comment]
@raid12345678 what you've done is perfect. The last step is to send it to a key server so that others can fetch your key form the server to perform verifications or encrypt messages and files to you etc.

Try this:
```
gpg --keyserver hkp://subset.pool.sks-keyservers.net --send-keys F6AC50287026C9BC7F37A19FA640A7F6529F3B79
```

Might take some time for it to appear on the key servers, but after some time you can go to http://subset.pool.sks-keyservers.net/ and find your public key 😃

**Comment by raid12345678** [comment]
Thank you sir! this has been done.@mitchellcash

**Review by ioncoincore — APPROVED** [review]
everything ok

**Pull request merged**
