### PR TITLE
[gitian][maintenance][org] Update gitian keys

### PR DESCRIPTION
**Pull request by ioncoincore**
Update gitian keys.txt and instructions in readme

### CODE REVIEW

**Comment by MitchellCash** [comment]
As briefly mentioned in #17 we don't need to add those additional keyservers because they are all already Synchronising Key Servers (SKS) and sync keys with one another anyway. One should not be different from the other.

**Proof of each:**
Ubuntu: https://keyserver.ubuntu.com/pks/lookup?op=stats
Debian: https://keyring.debian.org/ which they write `... although a copy of all updates will be forwarded to the keyserver network.`
MIT: https://pgp.mit.edu/pks/lookup?op=stats

So because they are all in sync, rather than picking a single point of failure we use the SKS pool to pick a server for us. Which is why just using `hkp://subset.pool.sks-keyservers.net` is satisfactory for the goals we are looking to achieve.

Using `subset.pool.sks-keyservers.net` also has the benefit of not running into issues for people using Elliptic Curve public keys.

```
This is a subset of the pool: At the moment it only includes servers updated to version 1.1.6. This pool support Elliptic Curve public keys as described in RFC6637 and those based on Curve25519 (Both Ed25519/eddsa and for encryption)
```

**Comment by ioncoincore** [comment]
point here is that it works with ubuntu keyserver and it is not new to me how sks works, and it is not a point of sks having them synced, server might be overloaded or unreachable, copy&paste does not cost me 0.001 seconds and I will get keys, looking or debuggin my own system for ability to test gitian, signing etc would be to much asked of a user. Check your gpg version too, which do you have, that as a note.

I disagree that having backup/alternative is bad and should not added, we might change a script to do it in one line.

```
Distributor ID:	LinuxMint
Description:	Linux Mint 19 Tara
Release:	19
Codename:	tara
```
ref https://github.com/ioncoincore/ion/issues/17#issuecomment-452613922

**Comment by FornaxA** [comment]
Mine is OK now - added fresh key.

I agree that redundancy is good. I my experience, the key servers are down, unreachable and generally unreliable more often than not.

**Review by ckti — APPROVED** [review]
Have added in my changed key as well

**Comment by cevap** [comment]
thx @ckti & @FornaxA , @MitchellCash can you add/check for missing keys and if there is anybody else who should be in this list?

**Comment by cevap** [comment]
I will merge this pull, we can delete those lines at any time. @MitchellCash if you still think this should not be merged, please reopen this issue

**Pull request merged**
