### PR TITLE
Update to conform to new snapcraft.io rules

### PR DESCRIPTION
**Pull request by ckti**
- Update to conform to new snapcraft.io rules
- Sanitize .desktop files

### CODE REVIEW

**Review by FornaxA — APPROVED** [review]
Looks like snap built correctly in your repo.
ACK

**Review by RdeWilde — APPROVED** [review]

**Comment by cevap** [comment]
this should not be merged for now, snapcraft has a bug and they are fixing it, reverting to v4.0.0 should work again together with ${SNAP}/ion.png, they had a problem with icons. We should not change anything for snap until the push a fix.

**Comment by cevap** [comment]
there is also another bug where it says that it was released but it wasnt, it happens when manual verification is requested, all packages in after that show up as released. Building snap itself is not broken it is just autoverify process

**Comment by RdeWilde** [comment]
It merged anyway?

**Comment by cevap** [comment]
what are you doing guys?

**Pull request merged**
